#!/usr/bin/env bash

# Changes the OSX Terminal app profile. Affects all tabs and windows.
#
# Usage: termprofile [profile name]

profile=$1

command="tell application \"Terminal\"
    repeat with w from 1 to count windows
        repeat with t from 1 to count tabs of window w
                set current settings of tab t of window w to (first settings set whose name is \"$profile\")
        end repeat
    end repeat
end tell"

echo "$command" | osascript